# ROS 2 example development environment Compose file.
#
# Roberto Masocco <robmasocco@gmail.com>
# Alessandro Tenaglia <alessandro.tenaglia42@gmail.com>
#
# January 27, 2022

version: "3.9"

# VS Code Development target
services:
  ros2vsc-dev:
    build:
      context: ./config
      network: host
      target: dev
    network_mode: "host"
    security_opt:
      - seccomp:unconfined
    environment:
      TERM: xterm-256color
      DISPLAY:
    cap_add:
      - SYS_PTRACE
    user: ros
    stdin_open: false
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/ros/workspace

  # VS Code Development with Nvidia GPU target
  ros2vsc-nvidia:
    build:
      context: ./config
      network: host
      target: nvidia
    network_mode: "host"
    security_opt:
      - seccomp:unconfined
    environment:
      TERM: xterm-256color
      DISPLAY:
    cap_add:
      - SYS_PTRACE
    user: ros
    stdin_open: false
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/ros/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
